In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\emmanuel\appdata\roaming\python\python314\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\emmanuel\appdata\roaming\python\python314\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\emmanuel\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\emmanuel\appdata\roaming\python\python314\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\emmanuel\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('INMET-2025-BH-PAMPULHA.CSV', encoding='latin-1', sep=';', skiprows=8, decimal=',')

In [4]:
df.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2025/01/01,0000 UTC,0.0,918.2,918.2,917.3,NaN,21.3,17.6,21.7,21.2,17.8,17.4,80.0,78.0,79.0,44.0,1.5,0.1,NaN
1,2025/01/01,0100 UTC,0.0,918.6,918.7,918.2,NaN,21.3,17.7,21.5,20.9,18.1,17.6,82.0,79.0,80.0,44.0,1.4,0.0,NaN
2,2025/01/01,0200 UTC,0.0,918.9,918.9,918.4,NaN,21.0,17.6,21.3,20.4,18.3,17.6,86.0,80.0,81.0,145.0,2.7,0.0,NaN
3,2025/01/01,0300 UTC,0.0,918.4,919.0,918.4,NaN,21.4,18.0,21.5,20.5,18.3,17.6,85.0,81.0,81.0,127.0,2.4,0.8,NaN
4,2025/01/01,0400 UTC,0.0,917.5,918.4,917.0,NaN,21.2,17.7,21.4,21.1,18.1,17.7,82.0,80.0,80.0,116.0,3.5,0.7,NaN

In [5]:
df = df.drop(columns=['Unnamed: 19'])
df.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2025/01/01,0000 UTC,0.0,918.2,918.2,917.3,NaN,21.3,17.6,21.7,21.2,17.8,17.4,80.0,78.0,79.0,44.0,1.5,0.1
1,2025/01/01,0100 UTC,0.0,918.6,918.7,918.2,NaN,21.3,17.7,21.5,20.9,18.1,17.6,82.0,79.0,80.0,44.0,1.4,0.0
2,2025/01/01,0200 UTC,0.0,918.9,918.9,918.4,NaN,21.0,17.6,21.3,20.4,18.3,17.6,86.0,80.0,81.0,145.0,2.7,0.0
3,2025/01/01,0300 UTC,0.0,918.4,919.0,918.4,NaN,21.4,18.0,21.5,20.5,18.3,17.6,85.0,81.0,81.0,127.0,2.4,0.8
4,2025/01/01,0400 UTC,0.0,917.5,918.4,917.0,NaN,21.2,17.7,21.4,21.1,18.1,17.7,82.0,80.0,80.0,116.0,3.5,0.7

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 19 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Data                                                   8760 non-null   str
 1   Hora UTC                                               8760 non-null   str
 2   PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                       8748 non-null   float64
 3   PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  8748 non-null   float64
 4   PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)        8747 non-null   float64
 5   PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)       8746 non-null   float64
 6   RADIACAO GLOBAL (Kj/m²)                                4714 non-null   float64
 7   TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)           8748 non-null   float64
 8   TEMPERATURA DO PONTO DE ORVALHO (°C)                   8748 non-null   float64
 9   TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)             8747 non-null   float64
 10  TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)             8747 non-null   float64
 11  TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)       8747 non-null   float64
 12  TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)       8746 non-null   float64
 13  UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)               8747 non-null   float64
 14  UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)               8747 non-null   float64
 15  UMIDADE RELATIVA DO AR, HORARIA (%)                    8748 non-null   float64
 16  VENTO, DIREÇÃO HORARIA (gr) (° (gr))                   8748 non-null   float64
 17  VENTO, RAJADA MAXIMA (m/s)                             8747 non-null   float64
 18  VENTO, VELOCIDADE HORARIA (m/s)                        8747 non-null   float64
dtypes: float64(17), str(2)
memory usage: 1.3 MB

In [7]:
df['RADIACAO GLOBAL (Kj/m²)'].count()

np.int64(4714)